version: '2'
services:
  web:
    build: "containers/tinyrss-web"
    ports:
      - "80:80/tcp"
    volumes:
      - "tinyrss_web:/var/www"
      - "tinyrss_certbot:/etc/letsencrypt"
    depends_on:
      - db

  db:
    image: "mariadb:latest"
    volumes:
      - "tinyrss_db:/var/lib/mysql"

  certbot:
    build: "containers/tinyrss-certbot"
    volumes:
      - "tinyrss_certbot:/etc/letsencrypt"
    depends_on:
      - web

  cron:
    build: "containers/tinyrss-cron"
    volumes:
      - "tinyrss_web:/var/www"
    depends_on:
      - db
volumes:
  tinyrss_web:
  tinyrss_certbot:
  tinyrss_db:
