FROM mariadb:latest
MAINTAINER dch.tai@gmail.com

ENV MYSQL_USER=tinyrss
ENV MYSQL_PASSWORD="tinyrss-root-password"

# Exposed already by mariadb:latest, re-added here for explicit documentation
VOLUME /var/lib/mysql
